### ISSUE TITLE
Feature request: Support SKLearn pipelines

### ISSUE THREAD

**Issue by dimtsi** [tvdboom/ATOM#2]
It would be really nice if you could also include sklearn pipelines as input to atom. 

Keep up the good work. Cheers! :D

**Comment by tvdboom** [comment]
I thought about it and the idea of atom's initializer is to get the dataset with which you want to work. A sklearn pipeline does not contain any data so that would still need to be provided. What you can do is add the pipeline as a custom transformer through the add method.

Example
`
atom = ATOMClassifier(X, y)
atom.add(sklearn_pipeline)
`

If you do this. Every transformer in the sklearn pipeline will be added to atom's pipeline. The only problem might arise if the pipeline has an estimator at the end. That is not allowed since atom manages its own models independently. In that case you should type `atom.add(pipeline[:-1])`.
