### ISSUE TITLE
Reload Error

### ISSUE THREAD

**Issue by chuwenhao123** [tvdboom/ATOM#30]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://tvdboom.github.io/ATOM/latest/contributing/).
- [X] The documentation does not mention anything about my problem.
- [X] There are no open or closed issues that are related to my problem.

### Description

I saved the model with save_data=True/False, but when I reloaded the file this error occurred:

AttributeError: Can't get attribute 'sqrt' on <module 'featuretools.primitives.base.transform_primitive_base' from '/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/featuretools/primitives/base/transform_primitive_base.py'>

![image](https://user-images.githubusercontent.com/51478550/157631352-41bee911-cba7-4bf0-9828-769ab7a1a464.png)
![image](https://user-images.githubusercontent.com/51478550/157631549-09f97e5b-bc85-4b7e-a90a-9e8034eb5ce2.png)

### Python and package version

- Python: 3.7.4
- ATOM: 4.13.0

**Comment by tvdboom** [comment]
Hi. Indeed, my previous solution wasn't good since it doesn't work when trying to unpickle the object. I am not sure right now how to solve this issue. I opened an issue in the featuretools github page (ATOM uses the featuretools package under the hood for these operations), see if someone there can help me. This is the link: [https://github.com/alteryx/featuretools/issues/1942](https://github.com/alteryx/featuretools/issues/1942). I'll come back to you as soon as I know more.

**Comment by tvdboom** [comment]
It appears it's not doable to pickle custom primitives. Instead, I created a PR to add the operators that are failing to featuretools' standard primitives (https://github.com/alteryx/featuretools/pull/1948) . If it's accepted, I can change the code in ATOM to fix the issue. Thus this issue will be fixed after the next release of featuretools. In the mean time, I suggest you don't use the `sqrt`, `log`, `sin`, `cos` and `tan` operators. The others should work fine.

**Comment by tvdboom** [comment]
Update: this error has been solved in the newest release v4.13.0.
